[ch22448] Create PD page - style updates
unicef/etools-partnership-management pull request #1472
Opened 2020-09-18 11:25 UTC by laza88

[ch22448] Create PD page - style updates

2020-09-29 17:34 UTC, acory requested changes

2020-09-29 17:34 UTC, acory commented on src_ts/components/app-modules/interventions/pages/new/intervention-new.template.ts
> +    ${sharedStylesPolymer()}
this component is in LitElement

2020-10-15 09:43 UTC, danNordlogic approved these changes

2020-10-15 14:43 UTC, acory approved these changes

2020-10-15 14:44 UTC, merged